### PR TITLE
Fixing hanging uploads

### LINKED ISSUE #790: Crash when checking response status code
We received a crash report, seems that we need to check that `resp` is not null before we check _`resp.StatusCode`:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x145c8f2]
goroutine 78 [running]:
github.com/Shopify/themekit/src/httpify.(*HTTPClient).doWithRetry(0xc0002b2800, 0xc00016e000, 0x14ee800, 0xc0000a8c30, 0x1, 0xc00034a190, 0x0)
        /Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:130 +0x102
github.com/Shopify/themekit/src/httpify.(*HTTPClient).do(0xc0002b2800, 0x15775a6, 0x3, 0xc0002cba00, 0x33, 0x14ee800, 0xc0000a8c30, 0xc0000a8c00, 0x100cead, 0x1556e60, ...)
        /Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:105 +0x5d1
github.com/Shopify/themekit/src/httpify.(*HTTPClient).Put(0xc0002b2800, 0xc0002cba00, 0x33, 0x14ee800, 0xc0000a8c30, 0xc0000a8c00, 0xd, 0x19fa1e0, 0x0)
        /Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:82 +0x7f
github.com/Shopify/themekit/src/shopify.Client.UpdateAsset(0xc000337960, 0xc, 0xc0002b0ce0, 0x20, 0x19dd860, 0xd, 0xd, 0x19fa1e0, 0x0, 0x0, ...)
        /Users/andyw8/src/github.com/Shopify/themekit/src/shopify/theme_client.go:293 +0x1fd
github.com/Shopify/themekit/cmd.perform(0xc000020b40, 0xc0000f0bd0, 0x26, 0x0, 0xc000215b20, 0x20)
        /Users/andyw8/src/github.com/Shopify/themekit/cmd/watch.go:123 +0xa44
github.com/Shopify/themekit/cmd.watch(0xc000020b40, 0xc00015c900, 0xc00015c960, 0x167bf00, 0x19fa450, 0x0, 0x0)
        /Users/andyw8/src/github.com/Shopify/themekit/cmd/watch.go:86 +0x6d7
github.com/Shopify/themekit/cmd.glob..func12.1(0xc000020b40, 0x0, 0x0)
        /Users/andyw8/src/github.com/Shopify/themekit/cmd/watch.go:58 +0x302
github.com/Shopify/themekit/src/cmdutil.forEachClient.func1(0x8, 0x159d220)
        /Users/andyw8/src/github.com/Shopify/themekit/src/cmdutil/util.go:288 +0x2e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00001e6f0, 0xc000508d40)
        /Users/andyw8/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/andyw8/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

### LINKED ISSUE #801: theme download gets stuck at 97%
Hi there,

I recently updated themekit to latest version (1.1.1) and since then it cannot download all the files...
I tried with 3 different themes and all of them get stuck around 97-98%

`[development] Warning, this is the live theme on XXXXX-THEME.`
`[development] 389|401 [===================================================================>--]  97 %`

Any thoughts on this?

Thanks

**OS**: Mac
**Themekit**: v1.1.1

### LINKED ISSUE #810: Invalid memory address
**Describe the bug**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x145c8f2]

**To Reproduce**
1. run command 'theme watch'
2. keep watching for more than 1 hour

**Expected behavior**
It should not crash

**Environment (please complete the following information):**
 - OS: MacOS 10.14 (Mojave)
- Themekit version (run theme version to check): ThemeKit 1.1.1 darwin/amd64
 - Editor [e.g. atom, sublime]: Sublime Text 3
 - Ignore: N/A

**Additional context**
It crashes even when only one theme is watched.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x145c8f2]

goroutine 59 [running]:
github.com/Shopify/themekit/src/httpify.(*HTTPClient).doWithRetry(0xc0003060c0, 0xc00022b000, 0x14ee800, 0xc000376150, 0x1, 0xc0003f40b0, 0x0)
	/Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:130 +0x102
github.com/Shopify/themekit/src/httpify.(*HTTPClient).do(0xc0003060c0, 0x15775a6, 0x3, 0xc000027ec0, 0x33, 0x14ee800, 0xc000376150, 0xc0003760c0, 0x100cead, 0x1556e60, ...)
	/Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:105 +0x5d1
github.com/Shopify/themekit/src/httpify.(*HTTPClient).Put(0xc0003060c0, 0xc000027ec0, 0x33, 0x14ee800, 0xc000376150, 0xc0003760c0, 0xd, 0x19fa1e0, 0x0)
	/Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:82 +0x7f
github.com/Shopify/themekit/src/shopify.Client.UpdateAsset(0xc0002f0390, 0xc, 0xc00002a420, 0x2a, 0x19dd860, 0xd, 0xd, 0x19fa1e0, 0x0, 0x0, ...)
	/Users/andyw8/src/github.com/Shopify/themekit/src/shopify/theme_client.go:293 +0x1fd
github.com/Shopify/themekit/cmd.perform(0xc0000ceb40, 0xc000450000, 0x18, 0x0, 0xc000681760, 0x20)
	/Users/andyw8/src/github.com/Shopify/themekit/cmd/watch.go:123 +0xa44
github.com/Shopify/themekit/cmd.watch(0xc0000ceb40, 0xc00020f140, 0xc00020f1a0, 0x167bf00, 0x19fa450, 0x0, 0x0)
	/Users/andyw8/src/github.com/Shopify/themekit/cmd/watch.go:86 +0x6d7
github.com/Shopify/themekit/cmd.glob..func12.1(0xc0000ceb40, 0x0, 0x0)
	/Users/andyw8/src/github.com/Shopify/themekit/cmd/watch.go:58 +0x302
github.com/Shopify/themekit/src/cmdutil.forEachClient.func1(0x8, 0x159d220)
	/Users/andyw8/src/github.com/Shopify/themekit/src/cmdutil/util.go:288 +0x2e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0001c0c00, 0xc000210220)
	/Users/andyw8/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/andyw8/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

### PR DESCRIPTION
**Pull request by tanema**
fixes #790 
fixes #801 
fixes #810 

Re-evaluating the retry mechanism, I realized that there was a fault in the if statements where the attempt count would only get incremented on timeouts and not for all other errors like 500s.

Here is the logic now
- if non-retryable http status (success or otherwise), return (100 =< code <= 428)
- if 499 then use retry-after header to block all requests until after the time limit then continue without incrementing attempt because this is not an error. I don't want to fail out of uploads because of 499s
- If request failed with host error, its fatal, return
- Otherwise, increment attempt and try again

### Warn Checklist
- [ ] This changes the interface and requires a Major/Minor version change.
- [x] I have :tophat:'d these changes by using the commands I changed by hand.
- [ ] I have added a dependancy to the project.
- [ ] I have considered any potential impact on [node-themekit](https://github.com/Shopify/node-themekit)

### CODE REVIEW

**Review by paulomarg — APPROVED** [review]
LGTM

File: src/httpify/client.go [hunk 1]
```diff
@@ -119,20 +118,23 @@ func (client *HTTPClient) doWithRetry(req *http.Request, body interface{}) (*htt
...
-			after, _ := strconv.ParseFloat(resp.Header.Get("Retry-After"), 10)
-			client.limit.ResetAfter(time.Duration(after))
-		} else if err != nil && strings.Contains(err.Error(), "no such host") {
+		} else if strings.Contains(err.Error(), "no such host") {
 			return nil, errConnectionIssue
 		}
+
+		attempt++
+		if attempt > client.maxRetry {
+			return resp, fmt.Errorf("request failed after %v retries with err: %v", client.maxRetry, err)
```
Comment (andyw8) [inline src/httpify/client.go:135]: `with error` ?

**Comment by andyw8** [comment]
@tanema were you able 🎩 locally? Guess it maybe be awkward.

**Comment by tanema** [comment]
I tophatted it with slow/timeouts and rate limits as well as the no host error/no connection errors.

**Review by andyw8 — APPROVED** [review]
