### PR TITLE
Action summary and return status

### LINKED ISSUE #738: "Skipped" text not visible in output
While working with @tanema earlier today, the text which should have appeared as dark grey on black was not visible.

His terminal is https://github.com/alacritty/alacritty

### LINKED ISSUE #822: `theme download` errors out "silently"
I had ignored `config/settings_data.json` in my `config.yml`.

```yaml
  ignore_files:
    - config/settings_data.json
```

I forgot I had it ignored and wanted to download latest settings data from the theme to make some simple change within the HTML data and upload it back up.

I ran:
```sh
theme download config/settings_data.json
```

Here's the full output:
```
> theme download config/settings_data.json
[development] Warning, this is the live theme on store-name.
No file paths matched the inputted arguments
```

`development` and `store-name` are in yellow, the rest of the text is in white (default color).

I missed this message unfortunately and thought everything went well.
I made the changes to (old) `settings_data.json` and pushed it to live site.
Only later did I realize that I never downloaded the latest `settings_data.json` from the live site.

I think this warning/error message should be more prominent. Something similar to how `[development]` is in yellow:

```
[development] WARNING: No file paths matched the inputted arguments!
```

### LINKED ISSUE #823: `theme deploy` errors silently
// related: [`theme download` errors out "silently"](https://github.com/Shopify/themekit/issues/822)

If any file fails to upload (deploy), for example, a section file fails to upload because it has invalid schema, then deployment continues. Eventually, having deployment continue and finish, breaks the website, as the section file wasn't deployed along with all the other files.

Failing to upload any file should immediately fail the whole deployment.

**To Reproduce**
1. Open any section file in the theme.
2. Change `"name"` property inside of `{% schema %}` block to: `"Collections Page Filter Header"` (anything longer than 25 characters would do
3. Run `theme deploy`

Or 

3.b Run `theme deploy sections/<your-section-name>.liquid`

Run `echo $?` immediately after.

<details><summary>Here's the sample output from `theme deploy`</summary>

```
...
[production] Updated assets/currencies.jquery.min.js
[production] Updated assets/icon-strong.png
[production] Updated assets/styles-min.css
[production] Updated assets/linkedin.png
[production] Updated assets/whatsapp.png
[production] Updated assets/twitter.png
[production] Updated assets/ico-select-menu.svg.liquid
[production] Updated assets/icon-moderate.png
[production] Updated assets/facebook.png
[production] Updated assets/theme.js.liquid
[production] (sections/collections-page-filter-header.liquid) Invalid schema: name is too long (max 25 characters)
[production] Updated assets/mail_old.png
[production] Updated assets/logo.png
[production] Updated assets/password.js.liquid
[production] Updated assets/script.js
[production] Updated layout/theme.liquid
[production] Updated assets/gift-card.scss.liquid
[production] Updated assets/pointing.png
[production] Updated assets/mail.png
[production] Updated assets/simulator.js
[production] Updated assets/password-page-background.jpg
[production] Updated assets/vendor-scripts.js
...
```

</details>

**Expected behavior**

The command should fail.

`echo $?` - prints last command's exit code. It's 0 for success and different from 0 for failure.
It should print a non-zero code.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOS 10.15.7
- Themekit version (run theme version to check): 1.1.2 darwin/amd64
 - Editor [e.g. atom, sublime]: sublime
 - Ignore: /

### PR DESCRIPTION
**Pull request by tanema**
fixes #823 
fixes #822 
fixes #738 

This PR is an effort to collect runtime file operations data and present them at the end of the runtime. This will have multiple effects
- Changed skipped color to cyan instead
- Showing the summary (download, upload, deleted, skipped, errors) of changes for `deploy` `remove` `download` `get` `new` with a consistent theme between all.
- Showing a count of errors
- Showing an output of the errors that were encountered
- Collecting error data to return status (still need to do) Currently themekit only sets error status if an error is returned however we need a way to return a general error if any were encountered during runtime
- Set error status when errors happened during file changes
- Make all fatal errors red.

image

Updated Screenshot:

image

### TODO
- [x] Testing
- [x] Opting-out for commands like `watch` other non-file operations like `open` are not shown since no actions take place.
- [x] Set status

### Warn Checklist
- [ ] This changes the interface and requires a Major/Minor version change.
- [x] I have :tophat:'d these changes by using the commands I changed by hand.
- [ ] I have added a dependancy to the project.
- [x] I have considered any potential impact on [node-themekit](https://github.com/Shopify/node-themekit)

### CODE REVIEW

File: src/shopify/theme_client.go [hunk 1]
```diff
@@ -142,7 +142,7 @@ func (c Client) GetShop() (Shop, error) {
 
 // Themes will return all the available themes on a domain.
 func (c Client) Themes() ([]Theme, error) {
-	resp, err := c.http.Get(APIPath + "themes.json", nil)
+	resp, err := c.http.Get(APIPath+"themes.json", nil)
```
Comment (andyw8) [inline src/shopify/theme_client.go:145]: Did `gofmt` change some of these?

Comment (tanema) [reply src/shopify/theme_client.go:145]: yup

File: src/cmdutil/summary.go [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+	"fmt"
+	"strings"
+	"sync/atomic"
+
+	"github.com/Shopify/themekit/src/colors"
+	"github.com/Shopify/themekit/src/file"
+)
+
+type cmdSummary struct {
+	actions, download, upload, skipped, removed int32
```
Comment (andyw8) [inline src/cmdutil/summary.go:13]: Maybe `downloaded` and `uploaded`?

File: src/shopify/theme_client.go (hunk 1 above)
Comment (andyw8) [reply src/shopify/theme_client.go:145]: I opened https://github.com/Shopify/themekit/pull/827 to keep the noise out of this one.
